### PR TITLE
Feature: Create API for Greetings Messages

### PR DESCRIPTION
**Pull request by zainsadaqat**
## In this pull request, I've done the following:

- Create new rails app for rails API
- Setup linters
- Create resource for Greeting (Model, Route, Controller)

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @zainsadaqat,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**

- The PR is nice 👌.
- The Readme file is good 👌.


## Required Changes ♻️
_Check the comments under the review._

- Nice job on your rails app, however, the tutorial is about creating two apps **`rails and react`** since you already created the API I suggest creating a react app and calling the  API using what you learned in the past weeks.

Capture web_25-3-2022_12324_github com
Capture web_25-3-2022_123228_github com
Capture web_25-3-2022_123249_github com


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
Hey @dasileker 
As per requirement, I am supposed to add the front-end repo link in the README file and the Backend repo link in the Frontend README file. It was a requirement that I've to submit the link of the Backend repo so that the reviewer could find the frontend repo link from the readme file.

**Comment by dasileker** [comment]
@ please add it also in the PR AND MAKE the header of the Front-end in the Readme file bigger and distinctive.

**Comment by AshakaE** [comment]
Hi @zainsadaqat , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
#### Thanks for approving the pull request @AshakaE 😊

**Pull request merged**
